service: the-marriage-of-ferris

provider:
  name: aws
  runtime: rust
  stage: dev
  memorySize: 128
  iamRoleStatments:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
        - "logs:DescribeLogStreams"
      Resource:
        - "*"

custom:
  rsvpTableName: ${self:service}-${opt:stage, self:provider.stage}-rsvp-table

environment:
  RSVP_TABLE_NAME: ${self:custom.rsvpTableName}

plugins:
  - serverless-rust

package:
  individually: true

functions:

  create-household:
    handler: create_household
    events:
      - http:
          path: household
          method: put

resources:
  Resources:
    rsvp-table:
      Type: AWS:DynamoDB::Table
      Properties:
        TableName: ${self:custom.rsvpTableName}
        AttributeDefinitions:
          - AttributeName: household_id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: household_id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
