service: the-marriage-of-ferris

provider:
  name: aws
  runtime: rust
  stage: dev
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
        - "logs:DescribeLogStreams"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "dynamodb:BatchWriteItem"
      Resource:
        - "*"
  environment:
    RSVP_TABLE_NAME: ${self:custom.rsvpTableName}

custom:
  rsvpTableName: ${self:service}-${opt:stage, self:provider.stage}-rsvp-table


plugins:
  - serverless-rust

package:
  individually: true

functions:

  create-household:
    handler: create_household
    events:
      - http:
          path: household
          method: put

resources:
  Resources:
    RSVPTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.rsvpTableName}
        AttributeDefinitions:
          - AttributeName: household_id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: household_id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5