service: the-marriage-of-ferris

provider:
  name: aws
  runtime: rust
  memorySize: 128
  custom:
    rsvpTableName: ${self:service}-${self:env}-rsvp-table
  environment:
    RSVP_TABLE_NAME: ${self:custom.rsvpTableName}

  iamRoleStatments:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
        - "logs:DescribeLogStreams"
      Resource:
        - "*"

plugins:
  - serverless-rust

package:
  individually: true

functions:

  create-household:
    handler: create_household
    events:
      - http:
          path: household
          method: put

resources:
  Resources:
    rsvp-table:
      Type: AWS:DynamoDB::Table
      Properties:
        TableName: ${self:custom.rsvpTableName}
        AttributeDefinitions:
          - AttributeName: household_id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: household_id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
