service: the-marriage-of-ferris

provider:
  name: aws
  runtime: rust
  memorySize: 128
  iamRoleStatments:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
        - "logs:DescribeLogStreams"
      Resource:
        - arn:aws:logs:*:*:*

plugins:
  - serverless-rust

package:
  individually: true

functions:
  test:
    handler: test
    events:
      - http:
          path: test
          method: get
