on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: setup-docker
      uses: docker-practice/actions-setup-docker@0.0.1
      with:
        docker_version: 19.09
        docker_channel: stable
    - name: npm install
      uses: actions/npm@master
      with:
        args: install
    - name: serverless deploy
      uses: wbprice/github-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
